// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Run() {
  return window['go']['client']['App']['Run']();
}

export function Context() {
  return window['go']['client']['App']['Context']();
}

export function CreateContext(arg1) {
  return window['go']['client']['App']['CreateContext'](arg1);
}

export function GetResources() {
  return window['go']['client']['App']['GetResources']();
}

export function IndexURI(arg1) {
  return window['go']['client']['App']['IndexURI'](arg1);
}

export function Menu() {
  return window['go']['client']['App']['Menu']();
}

export function OpenURI(arg1) {
  return window['go']['client']['App']['OpenURI'](arg1);
}

export function Query(arg1) {
  return window['go']['client']['App']['Query'](arg1);
}

export function Execute(arg1) {
  return window['go']['client']['App']['Execute'](arg1);
}

export function ExportContexts(arg1) {
  return window['go']['client']['App']['ExportContexts'](arg1);
}

export function GetContexts() {
  return window['go']['client']['App']['GetContexts']();
}

export function GetSources() {
  return window['go']['client']['App']['GetSources']();
}

export function OnBeforeClose(arg1) {
  return window['go']['client']['App']['OnBeforeClose'](arg1);
}
