// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {protocol} from '../models';
import {menu} from '../models';

export function Run():Promise<Error>;

export function Context():Promise<context.Context>;

export function CreateContext(arg1:string):Promise<protocol.CreateContextResponse>;

export function GetResources():Promise<protocol.GetResourcesResponse>;

export function IndexURI(arg1:string):Promise<protocol.IndexURIResponse>;

export function Menu():Promise<menu.Menu>;

export function OpenURI(arg1:string):Promise<any>;

export function Query(arg1:string):Promise<protocol.QueryResponse>;

export function Execute(arg1:string):Promise<protocol.ExecuteResponse>;

export function ExportContexts(arg1:Array<string>):Promise<protocol.ExportContextsResponse>;

export function GetContexts():Promise<protocol.GetContextsResponse>;

export function GetSources():Promise<protocol.GetSourcesResponse>;

export function OnBeforeClose(arg1:context.Context):Promise<boolean>;
